run:
  timeout: 1m
linters:
  enable-all: true
  disable:
    # deprecated
    - gomnd
    - execinquery
linters-settings:
  lll:
    line-length: 140
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/bavix)
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - dupl